const fs = require('fs');
const path = require('path');

console.log('[Build] Packaging PokeClicker Bot Bundle...');

const css = fs.readFileSync(path.join(__dirname, 'shared/pokeclicker-bot-ui.css'), 'utf8');
const core = fs.readFileSync(path.join(__dirname, 'shared/pokeclicker-bot-core.js'), 'utf8');
const ui = fs.readFileSync(path.join(__dirname, 'shared/pokeclicker-bot-ui.js'), 'utf8');

const bundle = `/**
 * PokéClicker Master Bot - Unified Bundle
 * Automatically generated by build.js
 */
(function() {
  'use strict';

  // 1. Inject Styles
  if (!document.getElementById('pokeclicker-bot-styles')) {
    const style = document.createElement('style');
    style.id = 'pokeclicker-bot-styles';
    style.textContent = ${JSON.stringify(css)};
    (document.head || document.documentElement).appendChild(style);
  }

  // 2. Load Core Engine
  ${core}

  // 3. Load UI Overlay
  ${ui}

  // 4. Bootstrap
  function launchBot() {
    if (window.PokeClickerBotCore && window.PokeClickerBotUI) {
      window.PokeClickerBotCore.init();
      window.PokeClickerBotUI.init();
      console.log('%c[PokeClicker Bot]%c Successfully Injected & Running!', 'background: #00f0ff; color: #000; font-weight: bold; padding: 2px 6px; border-radius: 4px;', 'color: #00f0ff; font-weight: bold;');
    } else {
      setTimeout(launchBot, 200);
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', launchBot);
  } else {
    launchBot();
  }
})();
`;

fs.writeFileSync(path.join(__dirname, 'shared/bundle.js'), bundle, 'utf8');
console.log('[Build] Wrote shared/bundle.js (' + bundle.length + ' bytes)');

// Copy to extension and desktop
fs.writeFileSync(path.join(__dirname, 'extension/bundle.js'), bundle, 'utf8');
console.log('[Build] Copied to extension/bundle.js');

fs.writeFileSync(path.join(__dirname, 'desktop/pokeclicker-bot.js'), bundle, 'utf8');
console.log('[Build] Copied to desktop/pokeclicker-bot.js');

console.log('[Build] Build complete!');
